# Build stage
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags='-s -w' -o server ./main.go

# Runtime stage
FROM scratch
COPY --from=builder /app/server /server
EXPOSE 9090
ENTRYPOINT ["/server"]
